version: musicfm_v01
wandb: true

params:
  batch_size: 5
  epoches: 1000000
  save_interval: 1
  log_interval: 100

datasets:
  track_list: res/track_ids.csv
  track_download_url: https://pri-alice.qa01.music-flo.com/reco/tracks
