params:
  batch_size: 4
  num_train_steps: 500000
  epoch_every_steps: 50000
  validation_check_every: 10000
  save_model_every: 10000
  save_logs_every: 10000

datasets:
  track_list: res/musicfm.csv
  track_download_url: https://pri-alice.qa01.music-flo.com/reco/tracks
